version: '3'

services:
  app:
    build: .
    volumes:
      - ./app:/app
      - ./data:/app/data
      - ./chroma_db:/app/chroma_db
    environment:
      - PYTHONPATH=/app
    command: python main.py