services:
  app:
    build: .
    volumes:
      - ./app:/app
      - ./data:/app/data
      - ./chroma_db:/app/chroma_db
    environment:
      - PYTHONPATH=/app
    depends_on:
      - chroma  # Garante que o ChromaDB inicia primeiro
    command: python main.py

  chroma:
    image: chromadb/chroma
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_db:/chroma/data